spring.application.name=Library-Management-System
server.port=8090
server.servlet.context-path=/lms.app/api

#Application properties
app.blobs.storage-path=${APP_BLOBS_STORAGE_PATH:D:/learning/projects/blob_objects}


# PostgreSQL Database
# Adding Env variable to run it on localhost and inside the docker containers
spring.datasource.url=jdbc:postgresql://${LMS_DB_HOST:localhost}:5433/lms_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

#Swagger URL
#http://localhost:8090/lms.app/api/swagger-ui/index.html

#Liquibase props
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml