spring.application.name=Library-Management-System
server.port=8090
server.servlet.context-path=/lms.app/api

#Application properties
app.blobs.storage-path=${APP_BLOBS_STORAGE_PATH:D:/learning/projects/blob_objects}


# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://lms_db:5432/lms_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

#Swagger URL
#http://localhost:8090/lms.app/api/swagger-ui/index.html