spring.application.name=Library-Management-System
server.port=8090
server.servlet.context-path=/lms.app/api


# PostgreSQL Database


spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=data
spring.datasource.password=data
